[package]
name = "iqos_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.7"
console = "0.15.11"
futures = "0.3.31"
rand = "0.9.0"
tokio = { version = "1.44.0", features = ["full"] }
tokio-macros = { version = "0.2.0-alpha.6" }
uuid = "1.15.1"
